# Die Spieler können andere Spieler verletzten.
PVP=true

# PvP ist mit Admin-Chat verbunden
PVPLogToolChat=true

# PvP ist mit Datei verbunden
PVPLogToolFile=true

# Die Spielwelt-Zeit wird angehalten wenn sich kein Spieler auf dem Server befindet
PauseEmpty=true

# Schaltet den globalen Chat ein oder aus.
GlobalChat=true

ChatStreams=s,r,a,w,y,sh,f,all

# Unregistrierte Spieler können sich mit dem Server verbinden.
Open=true

# Die erste Nachricht die im Chat-Panel sichtbar wird, sobald sich ein Spieler angemeldet hat. Du kannst RGB Farben nutzen um die Nachricht anzupassen, darüber hinaus kannst du < LINE> (ohne Leerzeichen) nutzen um Linien zu teilen. Mit \<RGB:1,0,0> Wird diese Nachricht rot dargestellt!
ServerWelcomeMessage=Welcome to Project Zomboid Multiplayer! <LINE> <LINE> To interact with the Chat panel: press Tab, T, or Enter. <LINE> <LINE> The Tab key will change the target stream of the message. <LINE> <LINE> Global Streams: /all <LINE> Local Streams: /say, /yell <LINE> Special Steams: /whisper, /safehouse, /faction. <LINE> <LINE> Press the Up arrow to cycle through your message history. Click the Gear icon to customize chat. <LINE> <LINE> Happy surviving!

# Zeigt den Benutzernamen über den Köpfen der Spieler an.
DisplayUserName=true

# Vor- und Nachnamen über Spielercharakteren anzeigen.
ShowFirstAndLastName=false

UsernameDisguises=false

HideDisguisedUserName=false

SwitchZombiesOwnershipEachUpdate=false

# Jeden neuen Spieler bei den angebenen Weltkoordinaten 'x,y,z' spawnen lassen. Wird ignoriert wenn: 0,0,0
SpawnPoint=0,0,0

# Die Spieler können PVP-Modus einzeln betreten und verlassen. Ein Spieler kann einen anderen Spieler nur verletzen, wenn ein oder beide Spieler im PvP-Modus befinden. Wenn SafetySystem
SafetySystem=true

# Zeigt ein Totenschädel-Symbol über die Köpfe der Spieler, die sich im PVP-Modus befinden.
ShowSafety=true

# Die Zeit die ein Spieler zum betreten oder verlassen des PVP-Modus braucht. Minimum=0 Maximum=1000 Standard=2
SafetyToggleTimer=2

# Die Verzögerung bevor ein Spieler wieder den PVP-Modus betreten oder verlassen kann. Minimum=0 Maximum=1000 Standard=3
SafetyCooldownTimer=3

# Minimum=0 Maximum=60 Standard=60
SafetyDisconnectDelay=60

# Gegenstände mit dem neue Spieler spawnen. Mehrere Gegenstände mittels einem Komma trennen. z.B.: Base.Axe, Base.BigHikingBag
SpawnItems=

# Der UDP-Port mit dem sich die Spieler zum Server verbinden. Minimum=0 Maximum=65535 Standard=16261
DefaultPort=16261

# Minimum=0 Maximum=65535 Standard=16262
UDPPort=16262

# Diese Nummer wird nach einem Soft-Reset geändert. Eine Änderung dieser Zahl löscht die Client-Sicherungsdateien (aber nicht Client-Spieler-Dateien). Minimum=0 Maximum=2147483647 Standard=893262781
ResetID=546195

# Gib hier die Mod-Lade-ID ein. Diese kann gefunden werden unter: \Steam\steamapps\workshop\modID\mods\modName\info.txt
Mods=damnlib;04vwTouran;49powerWagon;63Type2Van;63beetle;65banshee;66pontiacLeMans;67commando;67gt500;68firebird;69camaro;70barracuda;70dodge;75grandPrix;78amgeneralM35A2;78amgeneralM35A2extra;78amgeneralM49A2C;78amgeneralM50A3;78amgeneralM62;81deloreanDMC12;81deloreanDMC12BTTF;82porsche911;83amgeneralM923;83amgeneralM923extra;84buickElectra;84cadillacDeVille;84jeepXJ;84merc;85buickLeSabre;85chevyCaprice;85oldsmobileDelta88;85pontiacParisienne;86chevyCUCV;86fordE150;86fordE150dnd;86fordE150expanded;86fordE150mm;86fordE150pd;86oshkoshP19A;87buickRegal;87chevySuburban;87fordB700;90bmwE30;91fordLTD;91geoMetro;91nissan240sx;91range;92amgeneralM998;92amgeneralM998extra;92nissanGTR;93fordF350;93fordTaurus;93mustangSSP;98stagea;99fordCVPI;AlicesMultiWearVanilla;Authentic Z - Current;BB_CommonSenseFix.20;CSB42MP;CleanHotBar;NeatUI_Framework;CleanUI;DetailedDescriptionsForOccupationsAndTraits;DynamicHordeEventsB42;EatSmartInt;KillCount;MapSymbolSizeSlider;Military_Tool_Kit;ModLoadOrderSorter_b42;ModManager;ModernStatus;Neat_Building;Neat_Crafting;P4HasBeenRead;PROJECTRVInterior42;PWPNXB;Project_Cook;Project_Cook_Pixel_Icon_Pack;RainCleansBlood;ReducedWoodWeight2x41;TheShortcut;U.S. M998 Humvee by Papa_Chad;VB_CommonSense;VFExpansionReduxb42;manageContainers;tsarslib;vests42

# Gib hier den Ordnernamen der Mod ein wo diese zu finden ist. - \Steam\steamapps\workshop\modID\mods\modName\media\maps\
Map=map_distanciado;AZSpawn;Muldraugh, KY

# Kickt Spieler, deren Spiel-Dateien nicht mit dem  des Servers übereinstimmen.
DoLuaChecksum=true

DenyLoginOnOverloadedServer=true

# Listet den Server im Server-Browser. (Server mit Steam aktivierung werden auch im Steam-Server-Browser angezeigt)
Public=false

# Wird im Server-Browser angezeigt und möglicherweise auch im Steam-Server-Browser
PublicName=Dsischtig in Lenzburg

# Beschreibung wird im Server-Browser angezeigt. Mit   wird eine neue Zeile ihinzugefügt
PublicDescription=

# Maximale Anzahl von Spielern, die auf dem Server gleichzeitig sein können, ohne Admins. 
# WARNUNG: Server-Spielerzahlen über 32 führen möglicherweise zu schlechtem Karten-Streaming und Desynchronisation. Gehe bitte vorsichtig vor. Minimum=1 Maximum=100 Standard=32
MaxPlayers=32

# Der Ping-Limit in Millisekunden, bevor eine Spieler vom Server gekickt wird. Setze es auf 0, um es zu deaktivieren Minimum=0 Maximum=2147483647 Standard=0
PingLimit=0

# Gegenstände respawnen nicht in Gebäuden, die Spieler als Versteck markiert haben
SafehousePreventsLootRespawn=true

# Enfernt Spielerkonten aus der weißen Liste nach dem Tod. Verhindert einen neuen Charakter nach dem Tod zu erstellen.
DropOffWhiteListAfterDeath=false

# Alle arten von Feuer sind deaktiviert, ausgenommen Lagerfeuer
NoFire=false

# Wenn aktiv, jedes Mal wenn ein Spieler stirbt wird eine Nachricht im Chat angezeigt
AnnounceDeath=false

# Wenn aktiv, jedes Mal wenn ein Tier stirbt wird eine Nachricht im Chat angezeigt
AnnounceAnimalDeath=false

# Geladene Teile der Karte werden gespeichert, nachdem die angegebenen Echtzeit-Minuten vergangen sind. In der Regel wird die Karte gespeichert, nachdem der Spieler einen geladenen Bereich verlassen hat. Minimum=0 Maximum=2147483647 Standard=0
SaveWorldEveryMinutes=0

# Nicht-Administratoren können eine Versteck beanspruchen.
PlayerSafehouse=false

# Administratoren können ein Versteck beanspruchen.
AdminSafehouse=false

# Erlaubt Nicht-Mitgliedern das Versteck zu betreten.
SafehouseAllowTrepass=true

# Das Versteck kann durch Feuer schaden nehmen.
SafehouseAllowFire=true

# Erlaubt Nicht-Mitgliedern eines Verstecks, Gegenstände zu entnehmen.
SafehouseAllowLoot=true

# Spieler spawnen im Versteck das beansprucht wurde, bevor sie starben.
SafehouseAllowRespawn=false

# Spieler müssen so viele Spielwelt-Tage überlebt haben, bevor sie ein Versteck beanspruchen können. Minimum=0 Maximum=2147483647 Standard=0
SafehouseDaySurvivedToClaim=0

# Spieler werden automatisch aus einem Versteck entfernt, wenn diese nicht innerhalb der Echtzeit-Stunden das Versteck besucht haben. Minimum=0 Maximum=2147483647 Standard=144
SafeHouseRemovalTime=144

# Regelt ob Spieler Nichtwohngebäude beanspruchen können.
SafehouseAllowNonResidential=false

SafehouseDisableDisguises=true

# Minimum=0 Maximum=2147483647 Standard=20000
MaxSafezoneSize=20000

# Welt-Objekte können mit einem Vorschlaghammer zerstört werden.
AllowDestructionBySledgehammer=true

# Erlaube Spielern, Objekte nur in ihrem Unterschlupf zu zerstören (erfordere AllowDestructionBySledgehammer auf true).
SledgehammerOnlyInSafehouse=false

War=false

# Zeit in Sekunden, bevor der Krieg beginnt. Minimum=60 Maximum=2147483647 Standard=600
WarStartDelay=600

# Kriegsdauer in Sekunden. Minimum=60 Maximum=2147483647 Standard=3600
WarDuration=3600

# Trefferpunkt-Limit eines Verstecks. Minimum=0 Maximum=2147483647 Standard=3
WarSafehouseHitPoints=3

# Wird in den Client-Spieler-Dateien geschrieben, so dass Spieler keine Sicherungsdateien von 'Einzelspieler' oder einem anderen Server verwenden können.
ServerPlayerID=

# Der Port für das RCON (Remote Console) Minimum=0 Maximum=65535 Standard=27015
RCONPort=27015

# RCON Passwort (Wähle ein starkes Passwort)
RCONPassword=

# Aktiviert globalen Text Chat integration mit einem Discord Chat
DiscordEnable=false

# Discord Bot-Zugriffstoken
DiscordToken=

# Der Name des Discord Chats
DiscordChatChannel=

# Der Name des Discord-Protokollkanals
DiscordLogChannel=

# Der Discord-Befehlskanalname
DiscordCommandChannel=

# Die Slack-Webhook-URL
WebhookAddress=

# Spieler müssen das Passwort kennen um dem Server beizutreten.
Password=

# Begrenzt die Anzahl der Konten die ein Steam Benutzer auf diesem Server erstellen darf. Wird ignoriert wenn es sich um einen über Steam gehosteten Server handelt. Minimum=0 Maximum=2147483647 Standard=0
MaxAccountsPerUser=0

# Koop-/Splitscreen-Spieler zulassen
AllowCoop=true

# Die Spieler können zu jeder Zeit schlafen.
SleepAllowed=false

# Spieler werden müde und müssen schlafen.  Wird ignoriert, wenn SleepAllowed: false
SleepNeeded=false

# In Arbeit: Die Aktivierung dieser Einstellung kann zu einer visuellen Desynchronisation der Spielerpositionen führen.
KnockedDownAllowed=false

SneakModeHideFromOtherPlayers=true

UltraSpeedDoesnotAffectToAnimals=false

# Liste von Workshop Mod IDs für den Server zum Download. Getrennt durch ein Semikolon ( ; ). Beispiel: WorkshopItems=514427485;513111049
WorkshopItems=3171167894;3478633453;2900580391;3041122351;3005903549;3566868353;3447272250;2478247379;3026723485;3258343790;2991201484;2913633066;2873290424;3213391371;2799152995;3253385114;3379334330;2811383142;3596903773;3592777775;3409287192;2805630347;3418252689;3413704851;3418253716;3413706334;3428008364;2870394916;2566953935;3226885926;3196180339;3110911330;3110913021;3366300557;3008795514;3504401781;2409333430;2642541073;2846036306;3073430075;3088951320;3001592312;3315443103;2971246021;2959854619;2335368829;3717968421;3623609320;3461263912;3508537032;3437629766;3387957272;3716405632;3456212729;2553809727;2734705913;3423660713;3567084868;3451167732;3536052310;3502080466;2544353492;3543229299;3400528439;3490188370;2956146279;2377867605;3470659758;3750253491;3611718925;2650547917;3402491515;3390527264

# Steam-Benutzernamen und Avatare in der Spielerliste anzeigen. AN: true AUS: false NUR ADMINS: admin
SteamScoreboard=false

# Aktiviert das Steam-VAC-System
SteamVAC=true

# Versuche Port-Weiterleitungsregeln an einem UPnP fähigen Internet-Gateway automatisch zu konfigurieren.
UPnP=true

# Wenn TRUE (AN), Sprachchat ist aktiviert.
VoiceEnable=true

# Die minimale Entfernung in Feldern, über die der Sprachchat zu hören ist. Minimum=0.00 Maximum=100000.00 Standard=10.00
VoiceMinDistance=10.0

# Die maximale Entfernung in Feldern, über die der Sprachchat zu hören ist. Minimum=0.00 Maximum=100000.00 Standard=100.00
VoiceMaxDistance=100.0

# Richtungs-Audio für den Sprachchat.
Voice3D=true

# Minimum=10.00 Maximum=150.00 Standard=70.00
SpeedLimit=70.0

LoginQueueEnabled=false

# Minimum=20 Maximum=1200 Standard=60
LoginQueueConnectTimeout=60

# Leg hier die IP fest unter dem der Server zu erreichen ist. Für Netzwerkkonfigurationen mit mehreren IP-Adressen wie Serverfarmen
server_browser_announced_ip=

# Die Spieler können im Spiel respawnen, wo sie starben.
PlayerRespawnWithSelf=false

# Die Spieler können auf einem geteilten Bildschirm, beim Mitspieler respawnen.
PlayerRespawnWithOther=false

# Wie schnell vergeht die Zeit, wenn alle schlafen? Minimum=1.00 Maximum=100.00 Standard=40.00
FastForwardMultiplier=40.0

# Das Safehouse verhält sich wie ein normales Haus, wenn der Besitzer des Safehouses online ist (ist also sicher, wenn der Besitzer offline ist)
DisableSafehouseWhenOwnerConnected=false

# Wenn es TRUE (AN) ist, wird den Spielern erlaubt, Fraktionen/Gruppen zu bilden.
Faction=true

# Du musst X Tage überleben, bevor du eine Fraktionen/Gruppe erschaffen kannst. Minimum=0 Maximum=2147483647 Standard=0
FactionDaySurvivedToCreate=0

# Wieviele Spieler sind nötig, bevor der Fraktions/-Gruppenbesitzer ein spezielles Tag erstellen kann. Minimum=1 Maximum=2147483647 Standard=1
FactionPlayersRequiredForTag=1

# Deaktiviert die Funkübertragungen von Spielern mit beliebiger Zugriffsstufe.
DisableRadioStaff=false

# Deaktiviert die Funkübertragungen von Spielern mit der Zugriffsstufe 'admin'.
DisableRadioAdmin=true

# Deaktiviert die Funkübertragungen von Spielern mit der Zugriffsstufe 'gm'.
DisableRadioGM=true

# Deaktiviert die Funkübertragungen von Spielern mit der Zugriffsstufe 'overseer'.
DisableRadioOverseer=false

# Deaktiviert die Funkübertragungen von Spielern mit der Zugriffsstufe 'moderator'.
DisableRadioModerator=false

# Deaktiviert Funkübertragungen von unsichtbaren Spielern.
DisableRadioInvisible=true

# Semikolon-getrennte Liste von Befehlen, die nicht in die cmd.txt-Serverprotokoll geschrieben werden. -.vehicle.* bedeutet, dass kein Fahrzeugbefehl geschrieben wird. +vehicle.installPart bedeutet, dass dieser Befehl geschrieben wird.
ClientCommandFilter=-vehicle.*;+vehicle.damageWindow;+vehicle.fixPart;+vehicle.installPart;+vehicle.uninstallPart

# Strichpunkt getrennte Liste von Aktionen, die in das Serverprotokoll ClientActionLogs.txt geschrieben werden.
ClientActionLogs=ISEnterVehicle;ISExitVehicle;ISTakeEngineParts;

# Zeichne Änderungen an den Vorteilstufen der Spieler PerkLog.txt-Serverprotokoll auf
PerkLogs=true

# Maximale Anzahl von Gegenständen, die in einem Behälter gelegt werden können. Null bedeutet keine Begrenzung. Minimum=0 Maximum=9000 Standard=0
ItemNumbersLimitPerContainer=0

# Anzahl der Tage, bevor alte Blutspritzer entfernt werden.
# Entfernung erfolgt, wenn Kartenteile geladen werden.
# Zero bedeutet nie entfernen. Minimum=0 Maximum=365 Standard=0
BloodSplatLifespanDays=0

# Die Verwendung von nicht-ASCII (kyrillischen...) Zeichen im Benutzernamen ist erlaubt oder nicht.
AllowNonAsciiUsername=false

BanKickGlobalSound=true

# Bei TRUE (AN). Wenn HoursForCorpseRemoval ausgelöst wird, wird es auch die Leichen der Spieler entfernen.
RemovePlayerCorpsesOnCorpseRemoval=false

# Wenn aktiv, kann der Spieler den Button Alles löschen für Mülleimer verwenden.
TrashDeleteAll=false

# Wenn aktiv, kann ein Spieler zuschlagen, während er von einem anderen Spieler getroffen wird.
PVPMeleeWhileHitReaction=false

# Wenn aktiv, muss mit der Maus über einen Spielercharakter gezielt werden, um den Spielernamen anzuzeigen.
MouseOverToSeeDisplayName=true

# Wenn aktiv, verschwinden Spielercharaktere außerhalb des Sichtfelds des Spielers (wie Zombies).
HidePlayersBehindYou=true

# Schadensmultiplikator für PVP-Nahkampfangriffe Minimum=0.00 Maximum=500.00 Standard=30.00
PVPMeleeDamageModifier=30.0

# Schadensmultiplikator für PVP-Fernkampfangriffe Minimum=0.00 Maximum=500.00 Standard=50.00
PVPFirearmDamageModifier=50.0

# Ändert den Bereich, in dem Autos Zombies anziehen, niedrigere Werte können bei Server-Lags helfen. Minimum=0.00 Maximum=10.00 Standard=0.50
CarEngineAttractionModifier=0.5

# Spieler stoßen/schieben andere Spieler, wenn sie durch sie hindurchlaufen.
PlayerBumpPlayer=false

# Steuert die Anzeige von anderen Spielern auf der Karte im Spiel. 1 Minimum=1 Maximum=4 Standard=1
MapRemotePlayerVisibility=1

# Minimum=1 Maximum=300 Standard=5
BackupsCount=5

BackupsOnStart=true

BackupsOnVersionChange=true

# Minimum=0 Maximum=1500 Standard=0
BackupsPeriod=0

# Deaktiviert das Abschleppen von Fahrzeugen
DisableVehicleTowing=false

# Deaktiviert das Abschleppen von Anhängern
DisableTrailerTowing=false

# Deaktiviert das Abschleppen von ausgebrannten Fahrzeugen
DisableBurntTowing=false

# Pfad zur Datei mit der Liste der zu verbietenden Wörter. Jedes Wort muss in einer separaten Zeile stehen
BadWordListFile=

# Pfad zur Datei mit der Liste der erlaubten Wörter, auch wenn sie Schimpfwörter enthalten. Jedes Wort muss in einer separaten Zeile stehen.
GoodWordListFile=

# Was tun bei jemandem, der im Chat ein Schimpfwort benutzt? 1 - Bannen, 2 - Kicken, 3 - Verstoß in der Datenbank protokollieren, 4 - Stummschalten
BadWordPolicy=3

# Das Symbol oder der Textabschnitt, der das Schimpfwort ersetzen soll
BadWordReplacement=[HIDDEN]

# Deaktiviert den Anti-Cheat-Schutz.
AntiCheatSafety=2

# Deaktiviert den Anti-Cheat-Schutz für Charaktergeschwindigkeit.
AntiCheatSpeed=2

# Deaktiviert denCharakter no-clip Anti-Cheat.
AntiCheatNoClip=4

# Deaktiviert den Anti-Cheat-Schutz für Charaktertreffer.
AntiCheatHit=2

# Deaktiviert den Anti-Cheat für Packetprüfung.
AntiCheatPacketException=4

# Deaktiviert den Anti-Cheat-Schutz für Spielerbefugnisse.
AntiCheatPermission=2

# Deaktiviert den Anti-Cheat-Schutz für Spieler-EP.
AntiCheatXP=2

# Deaktiviert den Anti-Cheat-Schutz für Verstecke.
AntiCheatSafeHouse=2

# Deaktiviert den Spieler Anti-Cheat.
AntiCheatPlayer=2

# Deaktiviert den Anti-Cheat-Schutz für Checksummen.
AntiCheatChecksum=2

# Setzt die Aktualisierungsrate für Multiplayer in Sekunden. Statistiken deaktiviert wenn der Wert 0 ist. Minimum=0 Maximum=10 Standard=1
MultiplayerStatisticsPeriod=1

# Deakiviert das Scoreboard.
DisableScoreboard=false

# Admins werden in der Spielerliste nicht angezeigt.
HideAdminsInPlayerList=false

# Legt das Limit für die Verarbeitung von Netzwerkpaketen von jedem Client auf dem Server fest. Minimum=100 Maximum=1000 Standard=300
MaxPacketsPerSecond=300

# Zeigt die Koordinaten der Spielfigur in der unteren rechten Ecke an.
ShowCoordinates=false

# Der für die Weltgenerierung verwendete Seed.
# Wenn du diesen ändern möchtest, gib einen neuen Wert ein und lösche die Datei map_worldgen.bin in deinem Speicherordner.
Seed=xlEJhAsoOGJaLYTO

UsePhysicsHitReaction=false

# Minimum=64 Maximum=1024 Standard=200
ChatMessageCharacterLimit=200

# Minimum=1 Maximum=30 Standard=3
ChatMessageSlowModeTime=3